# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# Reduced subset of file from https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml

name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check the black styling
        run: |
          make style-check
      - name: Lint with flake8
        run: |
          make lint
      - name: Run unit tests
        run: |
          python -m pytest
